// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/documentv1/document.proto

package documentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId     string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	BatchId         string                 `protobuf:"bytes,4,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PipelineStage   string                 `protobuf:"bytes,6,opt,name=pipeline_stage,json=pipelineStage,proto3" json:"pipeline_stage,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Outputs         []*Output              `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	ProcessingError *ProcessingError       `protobuf:"bytes,9,opt,name=processing_error,json=processingError,proto3" json:"processing_error,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_documentv1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Document) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Document) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Document) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetPipelineStage() string {
	if x != nil {
		return x.PipelineStage
	}
	return ""
}

func (x *Document) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Document) GetOutputs() []*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *Document) GetProcessingError() *ProcessingError {
	if x != nil {
		return x.ProcessingError
	}
	return nil
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	S3Key         string                 `protobuf:"bytes,2,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	NativeTrigger string                 `protobuf:"bytes,3,opt,name=native_trigger,json=nativeTrigger,proto3" json:"native_trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_proto_documentv1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Output) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Output) GetNativeTrigger() string {
	if x != nil {
		return x.NativeTrigger
	}
	return ""
}

type ProcessingError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Extensions    map[string]string      `protobuf:"bytes,5,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessingError) Reset() {
	*x = ProcessingError{}
	mi := &file_proto_documentv1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessingError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingError) ProtoMessage() {}

func (x *ProcessingError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingError.ProtoReflect.Descriptor instead.
func (*ProcessingError) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProcessingError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProcessingError) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProcessingError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ProcessingError) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type CreateDocumentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_proto_documentv1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDocumentRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *CreateDocumentRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *CreateDocumentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateDocumentResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Document              *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	PresignedUrl          string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	PresignedUrlExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=presigned_url_expires_at,json=presignedUrlExpiresAt,proto3" json:"presigned_url_expires_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateDocumentResponse) Reset() {
	*x = CreateDocumentResponse{}
	mi := &file_proto_documentv1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentResponse) ProtoMessage() {}

func (x *CreateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentResponse.ProtoReflect.Descriptor instead.
func (*CreateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *CreateDocumentResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *CreateDocumentResponse) GetPresignedUrlExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PresignedUrlExpiresAt
	}
	return nil
}

type UpdateDocumentStatusRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ToStatus        string                 `protobuf:"bytes,2,opt,name=to_status,json=toStatus,proto3" json:"to_status,omitempty"`
	PipelineStage   string                 `protobuf:"bytes,3,opt,name=pipeline_stage,json=pipelineStage,proto3" json:"pipeline_stage,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ProcessingError *ProcessingError       `protobuf:"bytes,5,opt,name=processing_error,json=processingError,proto3" json:"processing_error,omitempty"`
	Outputs         []*Output              `protobuf:"bytes,6,rep,name=outputs,proto3" json:"outputs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDocumentStatusRequest) Reset() {
	*x = UpdateDocumentStatusRequest{}
	mi := &file_proto_documentv1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentStatusRequest) ProtoMessage() {}

func (x *UpdateDocumentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDocumentStatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDocumentStatusRequest) GetToStatus() string {
	if x != nil {
		return x.ToStatus
	}
	return ""
}

func (x *UpdateDocumentStatusRequest) GetPipelineStage() string {
	if x != nil {
		return x.PipelineStage
	}
	return ""
}

func (x *UpdateDocumentStatusRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UpdateDocumentStatusRequest) GetProcessingError() *ProcessingError {
	if x != nil {
		return x.ProcessingError
	}
	return nil
}

func (x *UpdateDocumentStatusRequest) GetOutputs() []*Output {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_documentv1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{6}
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type SubscribeStatusChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeStatusChangedRequest) Reset() {
	*x = SubscribeStatusChangedRequest{}
	mi := &file_proto_documentv1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeStatusChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeStatusChangedRequest) ProtoMessage() {}

func (x *SubscribeStatusChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_documentv1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeStatusChangedRequest.ProtoReflect.Descriptor instead.
func (*SubscribeStatusChangedRequest) Descriptor() ([]byte, []int) {
	return file_proto_documentv1_document_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeStatusChangedRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

var File_proto_documentv1_document_proto protoreflect.FileDescriptor

const file_proto_documentv1_document_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/documentv1/document.proto\x12\x17docuploader.document.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf4\x03\n" +
	"\bDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x19\n" +
	"\bbatch_id\x18\x04 \x01(\tR\abatchId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12%\n" +
	"\x0epipeline_stage\x18\x06 \x01(\tR\rpipelineStage\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x129\n" +
	"\aoutputs\x18\b \x03(\v2\x1f.docuploader.document.v1.OutputR\aoutputs\x12S\n" +
	"\x10processing_error\x18\t \x01(\v2(.docuploader.document.v1.ProcessingErrorR\x0fprocessingError\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Z\n" +
	"\x06Output\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x15\n" +
	"\x06s3_key\x18\x02 \x01(\tR\x05s3Key\x12%\n" +
	"\x0enative_trigger\x18\x03 \x01(\tR\rnativeTrigger\"\x8e\x02\n" +
	"\x0fProcessingError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12X\n" +
	"\n" +
	"extensions\x18\x05 \x03(\v28.docuploader.document.v1.ProcessingError.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x15CreateDocumentRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\xd1\x01\n" +
	"\x16CreateDocumentResponse\x12=\n" +
	"\bdocument\x18\x01 \x01(\v2!.docuploader.document.v1.DocumentR\bdocument\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12S\n" +
	"\x18presigned_url_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x15presignedUrlExpiresAt\"\xbb\x02\n" +
	"\x1bUpdateDocumentStatusRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tto_status\x18\x02 \x01(\tR\btoStatus\x12%\n" +
	"\x0epipeline_stage\x18\x03 \x01(\tR\rpipelineStage\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12S\n" +
	"\x10processing_error\x18\x05 \x01(\v2(.docuploader.document.v1.ProcessingErrorR\x0fprocessingError\x129\n" +
	"\aoutputs\x18\x06 \x03(\v2\x1f.docuploader.document.v1.OutputR\aoutputs\"5\n" +
	"\x12GetDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\"@\n" +
	"\x1dSubscribeStatusChangedRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId2\xcb\x03\n" +
	"\x0fDocumentService\x12q\n" +
	"\x0eCreateDocument\x12..docuploader.document.v1.CreateDocumentRequest\x1a/.docuploader.document.v1.CreateDocumentResponse\x12o\n" +
	"\x14UpdateDocumentStatus\x124.docuploader.document.v1.UpdateDocumentStatusRequest\x1a!.docuploader.document.v1.Document\x12]\n" +
	"\vGetDocument\x12+.docuploader.document.v1.GetDocumentRequest\x1a!.docuploader.document.v1.Document\x12u\n" +
	"\x16SubscribeStatusChanged\x126.docuploader.document.v1.SubscribeStatusChangedRequest\x1a!.docuploader.document.v1.Document0\x01BGZEgithub.com/opus2/docuploader/units/document-resolver/proto/documentv1b\x06proto3"

var (
	file_proto_documentv1_document_proto_rawDescOnce sync.Once
	file_proto_documentv1_document_proto_rawDescData []byte
)

func file_proto_documentv1_document_proto_rawDescGZIP() []byte {
	file_proto_documentv1_document_proto_rawDescOnce.Do(func() {
		file_proto_documentv1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_documentv1_document_proto_rawDesc), len(file_proto_documentv1_document_proto_rawDesc)))
	})
	return file_proto_documentv1_document_proto_rawDescData
}

var file_proto_documentv1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_documentv1_document_proto_goTypes = []any{
	(*Document)(nil),                      // 0: docuploader.document.v1.Document
	(*Output)(nil),                        // 1: docuploader.document.v1.Output
	(*ProcessingError)(nil),               // 2: docuploader.document.v1.ProcessingError
	(*CreateDocumentRequest)(nil),         // 3: docuploader.document.v1.CreateDocumentRequest
	(*CreateDocumentResponse)(nil),        // 4: docuploader.document.v1.CreateDocumentResponse
	(*UpdateDocumentStatusRequest)(nil),   // 5: docuploader.document.v1.UpdateDocumentStatusRequest
	(*GetDocumentRequest)(nil),            // 6: docuploader.document.v1.GetDocumentRequest
	(*SubscribeStatusChangedRequest)(nil), // 7: docuploader.document.v1.SubscribeStatusChangedRequest
	nil,                                   // 8: docuploader.document.v1.ProcessingError.ExtensionsEntry
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_proto_documentv1_document_proto_depIdxs = []int32{
	1,  // 0: docuploader.document.v1.Document.outputs:type_name -> docuploader.document.v1.Output
	2,  // 1: docuploader.document.v1.Document.processing_error:type_name -> docuploader.document.v1.ProcessingError
	9,  // 2: docuploader.document.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	9,  // 3: docuploader.document.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	8,  // 4: docuploader.document.v1.ProcessingError.extensions:type_name -> docuploader.document.v1.ProcessingError.ExtensionsEntry
	0,  // 5: docuploader.document.v1.CreateDocumentResponse.document:type_name -> docuploader.document.v1.Document
	9,  // 6: docuploader.document.v1.CreateDocumentResponse.presigned_url_expires_at:type_name -> google.protobuf.Timestamp
	2,  // 7: docuploader.document.v1.UpdateDocumentStatusRequest.processing_error:type_name -> docuploader.document.v1.ProcessingError
	1,  // 8: docuploader.document.v1.UpdateDocumentStatusRequest.outputs:type_name -> docuploader.document.v1.Output
	3,  // 9: docuploader.document.v1.DocumentService.CreateDocument:input_type -> docuploader.document.v1.CreateDocumentRequest
	5,  // 10: docuploader.document.v1.DocumentService.UpdateDocumentStatus:input_type -> docuploader.document.v1.UpdateDocumentStatusRequest
	6,  // 11: docuploader.document.v1.DocumentService.GetDocument:input_type -> docuploader.document.v1.GetDocumentRequest
	7,  // 12: docuploader.document.v1.DocumentService.SubscribeStatusChanged:input_type -> docuploader.document.v1.SubscribeStatusChangedRequest
	4,  // 13: docuploader.document.v1.DocumentService.CreateDocument:output_type -> docuploader.document.v1.CreateDocumentResponse
	0,  // 14: docuploader.document.v1.DocumentService.UpdateDocumentStatus:output_type -> docuploader.document.v1.Document
	0,  // 15: docuploader.document.v1.DocumentService.GetDocument:output_type -> docuploader.document.v1.Document
	0,  // 16: docuploader.document.v1.DocumentService.SubscribeStatusChanged:output_type -> docuploader.document.v1.Document
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_documentv1_document_proto_init() }
func file_proto_documentv1_document_proto_init() {
	if File_proto_documentv1_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_documentv1_document_proto_rawDesc), len(file_proto_documentv1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_documentv1_document_proto_goTypes,
		DependencyIndexes: file_proto_documentv1_document_proto_depIdxs,
		MessageInfos:      file_proto_documentv1_document_proto_msgTypes,
	}.Build()
	File_proto_documentv1_document_proto = out.File
	file_proto_documentv1_document_proto_goTypes = nil
	file_proto_documentv1_document_proto_depIdxs = nil
}
