// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/workspacev1/workspace.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workspace struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // ACTIVE | ARCHIVED
	RetentionPolicy  *RetentionPolicy       `protobuf:"bytes,4,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	EncryptionConfig *EncryptionConfig      `protobuf:"bytes,5,opt,name=encryption_config,json=encryptionConfig,proto3" json:"encryption_config,omitempty"`
	PipelineConfig   *PipelineConfig        `protobuf:"bytes,6,opt,name=pipeline_config,json=pipelineConfig,proto3" json:"pipeline_config,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{0}
}

func (x *Workspace) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Workspace) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Workspace) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workspace) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *Workspace) GetEncryptionConfig() *EncryptionConfig {
	if x != nil {
		return x.EncryptionConfig
	}
	return nil
}

func (x *Workspace) GetPipelineConfig() *PipelineConfig {
	if x != nil {
		return x.PipelineConfig
	}
	return nil
}

func (x *Workspace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workspace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RetentionPolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InputRetentionDays int32                  `protobuf:"varint,1,opt,name=input_retention_days,json=inputRetentionDays,proto3" json:"input_retention_days,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RetentionPolicy) Reset() {
	*x = RetentionPolicy{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionPolicy) ProtoMessage() {}

func (x *RetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionPolicy.ProtoReflect.Descriptor instead.
func (*RetentionPolicy) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{1}
}

func (x *RetentionPolicy) GetInputRetentionDays() int32 {
	if x != nil {
		return x.InputRetentionDays
	}
	return 0
}

type EncryptionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KmsAliasName  string                 `protobuf:"bytes,1,opt,name=kms_alias_name,json=kmsAliasName,proto3" json:"kms_alias_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptionConfig) Reset() {
	*x = EncryptionConfig{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionConfig) ProtoMessage() {}

func (x *EncryptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionConfig.ProtoReflect.Descriptor instead.
func (*EncryptionConfig) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptionConfig) GetKmsAliasName() string {
	if x != nil {
		return x.KmsAliasName
	}
	return ""
}

type PipelineConfig struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllowedExtensions         []string               `protobuf:"bytes,1,rep,name=allowed_extensions,json=allowedExtensions,proto3" json:"allowed_extensions,omitempty"`
	ForcedSlipsheetExtensions []string               `protobuf:"bytes,2,rep,name=forced_slipsheet_extensions,json=forcedSlipsheetExtensions,proto3" json:"forced_slipsheet_extensions,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *PipelineConfig) Reset() {
	*x = PipelineConfig{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineConfig) ProtoMessage() {}

func (x *PipelineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineConfig.ProtoReflect.Descriptor instead.
func (*PipelineConfig) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{3}
}

func (x *PipelineConfig) GetAllowedExtensions() []string {
	if x != nil {
		return x.AllowedExtensions
	}
	return nil
}

func (x *PipelineConfig) GetForcedSlipsheetExtensions() []string {
	if x != nil {
		return x.ForcedSlipsheetExtensions
	}
	return nil
}

type CreateWorkspaceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RetentionPolicy *RetentionPolicy       `protobuf:"bytes,2,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	PipelineConfig  *PipelineConfig        `protobuf:"bytes,3,opt,name=pipeline_config,json=pipelineConfig,proto3" json:"pipeline_config,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateWorkspaceRequest) Reset() {
	*x = CreateWorkspaceRequest{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkspaceRequest) ProtoMessage() {}

func (x *CreateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkspaceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateWorkspaceRequest) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *CreateWorkspaceRequest) GetPipelineConfig() *PipelineConfig {
	if x != nil {
		return x.PipelineConfig
	}
	return nil
}

func (x *CreateWorkspaceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateWorkspaceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId     string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	RetentionPolicy *RetentionPolicy       `protobuf:"bytes,2,opt,name=retention_policy,json=retentionPolicy,proto3" json:"retention_policy,omitempty"`
	PipelineConfig  *PipelineConfig        `protobuf:"bytes,3,opt,name=pipeline_config,json=pipelineConfig,proto3" json:"pipeline_config,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateWorkspaceRequest) GetRetentionPolicy() *RetentionPolicy {
	if x != nil {
		return x.RetentionPolicy
	}
	return nil
}

func (x *UpdateWorkspaceRequest) GetPipelineConfig() *PipelineConfig {
	if x != nil {
		return x.PipelineConfig
	}
	return nil
}

func (x *UpdateWorkspaceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_workspacev1_workspace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_workspacev1_workspace_proto_rawDescGZIP(), []int{6}
}

func (x *GetWorkspaceRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

var File_proto_workspacev1_workspace_proto protoreflect.FileDescriptor

const file_proto_workspacev1_workspace_proto_rawDesc = "" +
	"\n" +
	"!proto/workspacev1/workspace.proto\x12\x18docuploader.workspace.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x03\n" +
	"\tWorkspace\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12T\n" +
	"\x10retention_policy\x18\x04 \x01(\v2).docuploader.workspace.v1.RetentionPolicyR\x0fretentionPolicy\x12W\n" +
	"\x11encryption_config\x18\x05 \x01(\v2*.docuploader.workspace.v1.EncryptionConfigR\x10encryptionConfig\x12Q\n" +
	"\x0fpipeline_config\x18\x06 \x01(\v2(.docuploader.workspace.v1.PipelineConfigR\x0epipelineConfig\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"C\n" +
	"\x0fRetentionPolicy\x120\n" +
	"\x14input_retention_days\x18\x01 \x01(\x05R\x12inputRetentionDays\"8\n" +
	"\x10EncryptionConfig\x12$\n" +
	"\x0ekms_alias_name\x18\x01 \x01(\tR\fkmsAliasName\"\x7f\n" +
	"\x0ePipelineConfig\x12-\n" +
	"\x12allowed_extensions\x18\x01 \x03(\tR\x11allowedExtensions\x12>\n" +
	"\x1bforced_slipsheet_extensions\x18\x02 \x03(\tR\x19forcedSlipsheetExtensions\"\x87\x02\n" +
	"\x16CreateWorkspaceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12T\n" +
	"\x10retention_policy\x18\x02 \x01(\v2).docuploader.workspace.v1.RetentionPolicyR\x0fretentionPolicy\x12Q\n" +
	"\x0fpipeline_config\x18\x03 \x01(\v2(.docuploader.workspace.v1.PipelineConfigR\x0epipelineConfig\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\x8d\x02\n" +
	"\x16UpdateWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12T\n" +
	"\x10retention_policy\x18\x02 \x01(\v2).docuploader.workspace.v1.RetentionPolicyR\x0fretentionPolicy\x12Q\n" +
	"\x0fpipeline_config\x18\x03 \x01(\v2(.docuploader.workspace.v1.PipelineConfigR\x0epipelineConfig\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"8\n" +
	"\x13GetWorkspaceRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId2\xca\x02\n" +
	"\x10WorkspaceService\x12h\n" +
	"\x0fCreateWorkspace\x120.docuploader.workspace.v1.CreateWorkspaceRequest\x1a#.docuploader.workspace.v1.Workspace\x12h\n" +
	"\x0fUpdateWorkspace\x120.docuploader.workspace.v1.UpdateWorkspaceRequest\x1a#.docuploader.workspace.v1.Workspace\x12b\n" +
	"\fGetWorkspace\x12-.docuploader.workspace.v1.GetWorkspaceRequest\x1a#.docuploader.workspace.v1.WorkspaceBIZGgithub.com/opus2/docuploader/units/workspace-resolver/proto/workspacev1b\x06proto3"

var (
	file_proto_workspacev1_workspace_proto_rawDescOnce sync.Once
	file_proto_workspacev1_workspace_proto_rawDescData []byte
)

func file_proto_workspacev1_workspace_proto_rawDescGZIP() []byte {
	file_proto_workspacev1_workspace_proto_rawDescOnce.Do(func() {
		file_proto_workspacev1_workspace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_workspacev1_workspace_proto_rawDesc), len(file_proto_workspacev1_workspace_proto_rawDesc)))
	})
	return file_proto_workspacev1_workspace_proto_rawDescData
}

var file_proto_workspacev1_workspace_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_workspacev1_workspace_proto_goTypes = []any{
	(*Workspace)(nil),              // 0: docuploader.workspace.v1.Workspace
	(*RetentionPolicy)(nil),        // 1: docuploader.workspace.v1.RetentionPolicy
	(*EncryptionConfig)(nil),       // 2: docuploader.workspace.v1.EncryptionConfig
	(*PipelineConfig)(nil),         // 3: docuploader.workspace.v1.PipelineConfig
	(*CreateWorkspaceRequest)(nil), // 4: docuploader.workspace.v1.CreateWorkspaceRequest
	(*UpdateWorkspaceRequest)(nil), // 5: docuploader.workspace.v1.UpdateWorkspaceRequest
	(*GetWorkspaceRequest)(nil),    // 6: docuploader.workspace.v1.GetWorkspaceRequest
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_proto_workspacev1_workspace_proto_depIdxs = []int32{
	1,  // 0: docuploader.workspace.v1.Workspace.retention_policy:type_name -> docuploader.workspace.v1.RetentionPolicy
	2,  // 1: docuploader.workspace.v1.Workspace.encryption_config:type_name -> docuploader.workspace.v1.EncryptionConfig
	3,  // 2: docuploader.workspace.v1.Workspace.pipeline_config:type_name -> docuploader.workspace.v1.PipelineConfig
	7,  // 3: docuploader.workspace.v1.Workspace.created_at:type_name -> google.protobuf.Timestamp
	7,  // 4: docuploader.workspace.v1.Workspace.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: docuploader.workspace.v1.CreateWorkspaceRequest.retention_policy:type_name -> docuploader.workspace.v1.RetentionPolicy
	3,  // 6: docuploader.workspace.v1.CreateWorkspaceRequest.pipeline_config:type_name -> docuploader.workspace.v1.PipelineConfig
	1,  // 7: docuploader.workspace.v1.UpdateWorkspaceRequest.retention_policy:type_name -> docuploader.workspace.v1.RetentionPolicy
	3,  // 8: docuploader.workspace.v1.UpdateWorkspaceRequest.pipeline_config:type_name -> docuploader.workspace.v1.PipelineConfig
	4,  // 9: docuploader.workspace.v1.WorkspaceService.CreateWorkspace:input_type -> docuploader.workspace.v1.CreateWorkspaceRequest
	5,  // 10: docuploader.workspace.v1.WorkspaceService.UpdateWorkspace:input_type -> docuploader.workspace.v1.UpdateWorkspaceRequest
	6,  // 11: docuploader.workspace.v1.WorkspaceService.GetWorkspace:input_type -> docuploader.workspace.v1.GetWorkspaceRequest
	0,  // 12: docuploader.workspace.v1.WorkspaceService.CreateWorkspace:output_type -> docuploader.workspace.v1.Workspace
	0,  // 13: docuploader.workspace.v1.WorkspaceService.UpdateWorkspace:output_type -> docuploader.workspace.v1.Workspace
	0,  // 14: docuploader.workspace.v1.WorkspaceService.GetWorkspace:output_type -> docuploader.workspace.v1.Workspace
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_workspacev1_workspace_proto_init() }
func file_proto_workspacev1_workspace_proto_init() {
	if File_proto_workspacev1_workspace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_workspacev1_workspace_proto_rawDesc), len(file_proto_workspacev1_workspace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_workspacev1_workspace_proto_goTypes,
		DependencyIndexes: file_proto_workspacev1_workspace_proto_depIdxs,
		MessageInfos:      file_proto_workspacev1_workspace_proto_msgTypes,
	}.Build()
	File_proto_workspacev1_workspace_proto = out.File
	file_proto_workspacev1_workspace_proto_goTypes = nil
	file_proto_workspacev1_workspace_proto_depIdxs = nil
}
