{{ include "docuploader-chassis.serviceAccount" . }}
---
{{ include "docuploader-chassis.deployment" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.workloadName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.workloadName }}
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
