// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/batchv1/batch.proto

package batchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Batch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // OPEN | CLOSED
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Batch) Reset() {
	*x = Batch{}
	mi := &file_proto_batchv1_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Batch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Batch) ProtoMessage() {}

func (x *Batch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batchv1_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Batch.ProtoReflect.Descriptor instead.
func (*Batch) Descriptor() ([]byte, []int) {
	return file_proto_batchv1_batch_proto_rawDescGZIP(), []int{0}
}

func (x *Batch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *Batch) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Batch) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Batch) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Batch) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Batch) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId    string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBatchRequest) Reset() {
	*x = CreateBatchRequest{}
	mi := &file_proto_batchv1_batch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBatchRequest) ProtoMessage() {}

func (x *CreateBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batchv1_batch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBatchRequest.ProtoReflect.Descriptor instead.
func (*CreateBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_batchv1_batch_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBatchRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateBatchRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CloseBatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloseBatchRequest) Reset() {
	*x = CloseBatchRequest{}
	mi := &file_proto_batchv1_batch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseBatchRequest) ProtoMessage() {}

func (x *CloseBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batchv1_batch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseBatchRequest.ProtoReflect.Descriptor instead.
func (*CloseBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_batchv1_batch_proto_rawDescGZIP(), []int{2}
}

func (x *CloseBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *CloseBatchRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	mi := &file_proto_batchv1_batch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_batchv1_batch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_batchv1_batch_proto_rawDescGZIP(), []int{3}
}

func (x *GetBatchRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

var File_proto_batchv1_batch_proto protoreflect.FileDescriptor

const file_proto_batchv1_batch_proto_rawDesc = "" +
	"\n" +
	"\x19proto/batchv1/batch.proto\x12\x14docuploader.batch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x05Batch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"`\n" +
	"\x12CreateBatchRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"W\n" +
	"\x11CloseBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\",\n" +
	"\x0fGetBatchRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId2\x88\x02\n" +
	"\fBatchService\x12T\n" +
	"\vCreateBatch\x12(.docuploader.batch.v1.CreateBatchRequest\x1a\x1b.docuploader.batch.v1.Batch\x12R\n" +
	"\n" +
	"CloseBatch\x12'.docuploader.batch.v1.CloseBatchRequest\x1a\x1b.docuploader.batch.v1.Batch\x12N\n" +
	"\bGetBatch\x12%.docuploader.batch.v1.GetBatchRequest\x1a\x1b.docuploader.batch.v1.BatchBAZ?github.com/opus2/docuploader/units/batch-resolver/proto/batchv1b\x06proto3"

var (
	file_proto_batchv1_batch_proto_rawDescOnce sync.Once
	file_proto_batchv1_batch_proto_rawDescData []byte
)

func file_proto_batchv1_batch_proto_rawDescGZIP() []byte {
	file_proto_batchv1_batch_proto_rawDescOnce.Do(func() {
		file_proto_batchv1_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_batchv1_batch_proto_rawDesc), len(file_proto_batchv1_batch_proto_rawDesc)))
	})
	return file_proto_batchv1_batch_proto_rawDescData
}

var file_proto_batchv1_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_batchv1_batch_proto_goTypes = []any{
	(*Batch)(nil),                 // 0: docuploader.batch.v1.Batch
	(*CreateBatchRequest)(nil),    // 1: docuploader.batch.v1.CreateBatchRequest
	(*CloseBatchRequest)(nil),     // 2: docuploader.batch.v1.CloseBatchRequest
	(*GetBatchRequest)(nil),       // 3: docuploader.batch.v1.GetBatchRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_batchv1_batch_proto_depIdxs = []int32{
	4, // 0: docuploader.batch.v1.Batch.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: docuploader.batch.v1.Batch.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: docuploader.batch.v1.BatchService.CreateBatch:input_type -> docuploader.batch.v1.CreateBatchRequest
	2, // 3: docuploader.batch.v1.BatchService.CloseBatch:input_type -> docuploader.batch.v1.CloseBatchRequest
	3, // 4: docuploader.batch.v1.BatchService.GetBatch:input_type -> docuploader.batch.v1.GetBatchRequest
	0, // 5: docuploader.batch.v1.BatchService.CreateBatch:output_type -> docuploader.batch.v1.Batch
	0, // 6: docuploader.batch.v1.BatchService.CloseBatch:output_type -> docuploader.batch.v1.Batch
	0, // 7: docuploader.batch.v1.BatchService.GetBatch:output_type -> docuploader.batch.v1.Batch
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_batchv1_batch_proto_init() }
func file_proto_batchv1_batch_proto_init() {
	if File_proto_batchv1_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_batchv1_batch_proto_rawDesc), len(file_proto_batchv1_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_batchv1_batch_proto_goTypes,
		DependencyIndexes: file_proto_batchv1_batch_proto_depIdxs,
		MessageInfos:      file_proto_batchv1_batch_proto_msgTypes,
	}.Build()
	File_proto_batchv1_batch_proto = out.File
	file_proto_batchv1_batch_proto_goTypes = nil
	file_proto_batchv1_batch_proto_depIdxs = nil
}
